controller_list:
  - name: fake_interbotix_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - waist
      - shoulder
      - elbow
      - forearm_roll
      - wrist_angle
      - wrist_rotate
  - name: fake_interbotix_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger
initial:  # Define initial robot poses per group
  - group: interbotix_arm
    pose: Home
  - group: interbotix_gripper
    pose: Open